### PR TITLE
Fixes #27

### LINKED ISSUE #27: Ignoring special ply tags
I had some problems loading a .ply file made/edited with CloudCompare.
The header looks like this:

```
ply
format ascii 1.0
comment Author: CloudCompare (TELECOM PARISTECH/EDF R&D)
obj_info Generated by CloudCompare!
```

The problem is that the tag "obj_info" is not supported by the library,
resulting in an `IOException: Unsupported header entry: obj_info`.

The problem is in the following check (PlyReaderFile.java):
```
else if (!line.startsWith("comment ")) {
                throw new IOException("Unsupported header entry: " + line);
            }
```

I'm not sure what is the best way to fix this, probably just raising a warning and ignoring the unkown tag might be safer.

### PR DESCRIPTION
**Pull request by LakeIshikawa**
Fixes #27

### CODE REVIEW

**Comment by smurn** [comment]
Yep, that is the change I had in mind. Unfourtunately the pull-request contains code style changes I don't agree with:

* It is considered best pratice to list imports individually instead of using wildcards (https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports)

* Functions should be decorated with @Overwrite if they implement an interface or overwrite a base class (https://google.github.io/styleguide/javaguide.html#s6.1-override-annotation).

I'm ok with the additions to .gitignore.

I appreciate your effort! This is exactly the solution I had in mind. Would be great if you could clean up the pull request so that I can merge it.

Thanks,
Stefan

**Comment by LakeIshikawa** [comment]
Wow I'm sorry, I was getting the "@Override" thing completely wrong, I apologize.
My IDE was set at language level 1.5 while I thought it was set to 1.8 and it hinted "Set language level to 1.6 to support interface methods' @Override", and I misunderstood.

So I put all the @Override back and restored the original imports (that was my IDE that did the refactoring).  Hope it's ok now!

**Comment by LakeIshikawa** [comment]
And I just realized I added that property to set the language level to 1.8.  Is that ok or should it be 1.6?

**Comment by smurn** [comment]
Maven defaults to 1.5 and jPLY missed to set it correctly in the pom. You found another bug, thanks!

I'm pretty sure that jPLY would still run on 1.6. So, technically speaking, setting it to 1.6 would be correct to ensure maximal compatibility. At least until we want to use some of the newer features in jPLY. 

Do you have the time to set it to 1.6? If not, I'll just merge the pull-request as is. It is just a minor detail.

many thanks,
Stefan

**Comment by LakeIshikawa** [comment]
I just set it back to 1.6!
Hope it's ok now ^^

**Comment by smurn** [comment]
Perfect! 
Thanks your your patience!

**Comment by LakeIshikawa** [comment]
No problems :)
Looking forward to see the patch released on maven eventually! ^^

**Comment by smurn** [comment]
Yea, me too. I haven't released to the repository in years. What I need is a quiet weekend to figure the process out again. You brought jPLY back to my attention, I'll see it done.

**Pull request merged**
